const types = {
  GET_ALL_PRODUTOS: 'GET_ALL_PRODUTOS',
  GET_ONE_PRODUTO: 'GET_ONE_PRODUTO',
  SET_PRODUTOS_LOADING: 'SET_PRODUTOS_LOADING',

  SET_USUARIO_LOADING: 'SET_USUARIO_LOADING',
  SET_USUARIO_ATUAL: 'SET_USUARIO_ATUAL',
  LOGOUT_USUARIO: 'LOGOUT_USUARIO',

  GET_ALL_CATEGORIAS: 'GET_ALL_CATEGORIAS',
  GET_ONE_CATEGORIA: 'GET_ONE_CATEGORIA',

  GET_CARRINHO: 'GET_CARRINHO',
  SET_CART_LOADING: 'SET_CART_LOADING',

  SET_PAGAMENTO: 'SET_PAGAMENTO',
  SET_PAGAMENTO_LOADING: 'SET_PAGAMENTO_LOADING',
  GET_FRETE: 'GET_FRETE',
  SET_FRETE_LOADING: 'SET_FRETE_LOADING',

  SET_ERRORS: 'SET_ERRORS'
};

export default types;
