const types = {
  GET_ALL_PRODUTOS: 'GET_ALL_PRODUTOS',
  GET_ONE_PRODUTO: 'GET_ONE_PRODUTO',
  SET_PRODUTOS_LOADING: 'SET_PRODUTOS_LOADING',

  SET_USUARIO_LOADING: 'SET_USUARIO_LOADING',
  SET_USUARIO_ATUAL: 'SET_USUARIO_ATUAL',
  LOGOUT_USUARIO: 'LOGOUT_USUARIO',

  GET_ALL_CATEGORIAS: 'GET_ALL_CATEGORIAS',
  GET_ONE_CATEGORIA: 'GET_ONE_CATEGORIA',

  SET_ERRORS: 'SET_ERRORS'
};

export default types;
